### ISSUE TITLE
ctest failures in released version 0.9.8

### ISSUE THREAD

**Issue by daym** [gnudatalanguage/gdl#356] opened 2018-06-15 05:49 UTC
There are ctest failures in the released version:

```
95% tests passed, 11 tests failed out of 202

Total Test time (real) =  63.44 sec

The following tests FAILED:
         93 - test_fft_leak.pro (Failed)
        102 - test_finite.pro (Failed)
        103 - test_fix.pro (Failed)
        118 - test_image_statistics.pro (Failed)
        140 - test_n_tags.pro (Failed)
        142 - test_obj_isa.pro (Failed)
        144 - test_parse_url.pro (Failed)
        166 - test_resolve_routine.pro (Failed)
        168 - test_rounding.pro (Failed)
        190 - test_total.pro (Failed)
        199 - test_wordexp.pro (Failed)
Errors while running CTest
make[4]: *** [Makefile:133: test] Error 8
```

Is that expected?

**Comment by slayoo** [comment] 2018-06-15 06:54
Thanks for reporting it.

Unfortunately, it is expected for some tests to fail as of now, but - at least in my opinion - we should ship the next release with those tests either fixed or disabled. We have currently test execution set up on Travis and Appveyor resulting in Linux, OSX and Winsows runs - this should help.

Let me close this ticket and suggest to follow up on discussion in one the following tickets:
- #327 - list of test failures on Appveyor
- #13 - list of test failures on Travis
- #104 - list of test routines written but not executed yet during "make check"
(the tests that were failing on Appveyor and Travis at the time of the introduction of these platforms are temporarily disables to allow regression testing)

Thanks again, help very welcome in improving the situation!

**Closed as completed by slayoo** 2018-06-15 06:54 UTC

**Comment by alaingdl** [comment] 2018-06-15 07:00
hi

normal ! some tests must failed to help not to forgot we still have issues in the code !

what do you mean by "released version" ? 0.9.8.tgz ?

on which system are you, because some tests you listed are "never" suppose to fail !

**Comment by slayoo** [comment] 2018-06-15 07:07
Perhaps we should move those not-to-forget tests into a "sandbox" folder for use by developers only.
Having them within release files must cause serious confusion for users and especially packagers.

**Comment by daym** [comment] 2018-06-15 07:15
Yeah, I'm a packager for the Guix system distribution. We usually run tests to make sure we packaged it correctly. So this is not ideal...

@alaingdl

>what do you mean by "released version" ? 0.9.8.tgz ?

Yes.

>on which system are you, because some tests you listed are "never" suppose to fail !

GNU Guix, with a GDL package written by me.

More details follow once it's done building:

```
 93/202 Test  #93: test_fft_leak.pro ..................***Failed    1.04 sec
% Compiled module: TEST_FFT_LEAK.
% TEST_FFT_LEAK:       13 case of memory leak when calling FFT have been found
...
102/202 Test #102: test_finite.pro ....................***Failed   11.38 sec
% Compiled module: TEST_FINITE.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_FINITE_BASIC:   NO errors encountered during TEST_FINITE_BASIC tests  
% Compiled module: ERRORS_CUMUL.
% TEST_FINITE_BASIC:   NO errors encountered during TEST_FINITE_BASIC tests  
% Compiled module: ADD_ERROR.
% TEST_FINITE_BASIC: Error on operation : problem with Case        5
% TEST_FINITE_BASIC: Error on operation : problem with Case        8
% TEST_FINITE_BASIC:   2 errors encountered during TEST_FINITE_BASIC tests  
...
103/202 Test #103: test_fix.pro .......................***Failed    0.07 sec
% Compiled module: TEST_FIX.
% Compiled module: GIVE_LIST_NUMERIC.
% Compiled module: ADD_ERROR.
% TEST_FIX_NAN_INF: Error on operation : pb with type : BYTE
exp :   0   0  10 246   0   0   0   0
res :   0   0  10 246   0   0 255   0
% TEST_FIX_NAN_INF: Error on operation : pb with type : INT
exp :       0       0      10     -10       0       0       0       0
res :       0       0      10     -10       0       0   32767  -32768
% TEST_FIX_NAN_INF: Error on operation : pb with type : LONG
exp :           0           0          10         -10 -2147483648 -2147483648
 -2147483648 -2147483648
res :           0           0          10         -10 -2147483648 -2147483648
  2147483647 -2147483648
% TEST_FIX_NAN_INF: Error on operation : pb with type : LONG64
exp :                     0                     0                    10
                   -10  -9223372036854775808  -9223372036854775808
  -9223372036854775808  -9223372036854775808
res :                     0                     0                    10
                   -10  -9223372036854775808  -9223372036854775808
   9223372036854775807  -9223372036854775808
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_FIX_NAN_INF:   4 errors encountered during TEST_FIX_NAN_INF tests  
% Compiled module: ERRORS_CUMUL.
...
118/202 Test #118: test_image_statistics.pro ..........***Failed    0.13 sec
% Compiled module: TEST_IMAGE_STATISTICS.
% Compiled module: FILE_SEARCH_FOR_TESTSUITE.
% Compiled module: PATH_SEP.
% Compiled module: QUERY_IMAGE.
% WARNING: your version of the GraphicsMagick library will truncate images to 16 bits per pixel
% Compiled module: READ_JPEG.
% Compiled module: IMAGE_STATISTICS.
% Compiled module: STDDEV.
% Compiled module: VARIANCE.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_IMAGE_STATISTICS: 
=============================================================
% TEST_IMAGE_STATISTICS: 
=                                                           =
% TEST_IMAGE_STATISTICS: 
=  4 errors encountered during TEST_IMAGE_STATISTICS tests  =
% TEST_IMAGE_STATISTICS: 
=                                                           =
% TEST_IMAGE_STATISTICS: 
=============================================================
...
140/202 Test #140: test_n_tags.pro ....................***Failed    0.08 sec
% Compiled module: TEST_N_TAGS.
% Compiled module: GIVE_LIST_NUMERIC.
% Compiled module: ADD_ERROR.
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<BYTE>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<INT>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<LONG>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<FLOAT>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<DOUBLE>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<COMPLEX>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<UINT>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<ULONG>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<LONG64>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<ULONG64>>
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_NTAGS_BY_TYPE:   10 errors encountered during TEST_NTAGS_BY_TYPE tests  
% Compiled module: ERRORS_CUMUL.
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<BYTE>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<INT>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<UINT>>
% TEST_NTAGS_BY_TYPE:   3 errors encountered during TEST_NTAGS_BY_TYPE tests  
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<BYTE>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<INT>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<LONG>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<FLOAT>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<DOUBLE>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<COMPLEX>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<UINT>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<ULONG>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<LONG64>>
% TEST_NTAGS_BY_TYPE: Error on operation : /length case <<ULONG64>>
% TEST_NTAGS_BY_TYPE:   10 errors encountered during TEST_NTAGS_BY_TYPE tests  
% TEST_NTAGS_MIXING_TYPE: Error on operation : /length case 47
% TEST_NTAGS_MIXING_TYPE,: 
  1 errors encountered during TEST_NTAGS_MIXING_TYPE, tests  
...
142/202 Test #142: test_obj_isa.pro ...................***Failed    0.06 sec
% Compiled module: TEST_OBJ_ISA.
% TEST_OBJ_ISA: Errors in Testing LIST
% TEST_OBJ_ISA: Errors in Testing OBJARR
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_OBJ_ISA: ====================================================
% TEST_OBJ_ISA: =                                                  =
% TEST_OBJ_ISA: =  2 errors encountered during TEST_OBJ_ISA tests  =
% TEST_OBJ_ISA: =                                                  =
% TEST_OBJ_ISA: ====================================================
...
144/202 Test #144: test_parse_url.pro .................***Failed    0.07 sec
% Compiled module: TEST_PARSE_URL.
% PARSE_URL: URL fragment left out: #etc
% Compiled module: ERRORS_ADD.
% TEST_PARSE_URL_IPV6: Error on operation : { http user @pass host  path argument?value}
Case :        0
expected  : { http user @pass host  path argument?value}
processed : { http user @pass host  /path argument?value}
% TEST_PARSE_URL_IPV6: Error on operation : { http   [FEDC:BA98:7654:3210:FEDC:BA98:7654:3210] 80 index.html }
Case :        1
expected  : { http   [FEDC:BA98:7654:3210:FEDC:BA98:7654:3210] 80 index.html }
processed : { http   [FEDC:BA98:7654:3210:FEDC:BA98:7654:3210] 80 /index.html }
% TEST_PARSE_URL_IPV6: Error on operation : { http   [1080:0:0:0:8:800:200C:417A]  index.html }
Case :        2
expected  : { http   [1080:0:0:0:8:800:200C:417A]  index.html }
processed : { http   [1080:0:0:0:8:800:200C:417A]  /index.html }
% TEST_PARSE_URL_IPV6: Error on operation : { http   [1080::8:800:200C:417A]  foo }
Case :        4
expected  : { http   [1080::8:800:200C:417A]  foo }
processed : { http   [1080::8:800:200C:417A]  /foo }
% TEST_PARSE_URL_IPV6: Error on operation : { http   [::192.9.5.5]  ipng }
Case :        5
expected  : { http   [::192.9.5.5]  ipng }
processed : { http   [::192.9.5.5]  /ipng }
% TEST_PARSE_URL_IPV6: Error on operation : { http   [::FFFF:129.144.52.38] 80 index.html }
Case :        6
expected  : { http   [::FFFF:129.144.52.38] 80 index.html }
processed : { http   [::FFFF:129.144.52.38] 80 /index.html }
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_PARSE_URL_IPV6: 
  6 errors encountered during TEST_PARSE_URL_IPV6 tests  
% Compiled module: ERRORS_CUMUL.
% TEST_PARSE_URL_PORT: Error on operation : { http   someserver.com 80 path/to/firstfile.dat }
Case :        0
expected  : { http   someserver.com 80 path/to/firstfile.dat }
processed : { http   someserver.com  /path/to/firstfile.dat }
% TEST_PARSE_URL_PORT: Error on operation : { http   someserver.com  path/to/firstfile.dat }
Case :        1
expected  : { http   someserver.com  path/to/firstfile.dat }
processed : { http   someserver.com  /path/to/firstfile.dat }
% TEST_PARSE_URL_PORT: Error on operation : { http   someserver.com 1 path/to/firstfile.dat }
Case :        2
expected  : { http   someserver.com 1 path/to/firstfile.dat }
processed : { http   someserver.com 1 /path/to/firstfile.dat }
% TEST_PARSE_URL_PORT: Error on operation : { http   someserver.com 1234 path/to/firstfile.dat }
Case :        3
expected  : { http   someserver.com 1234 path/to/firstfile.dat }
processed : { http   someserver.com 1234 /path/to/firstfile.dat }
% TEST_PARSE_URL_PORT: Error on operation : { http   someserver.com && path/to/firstfile.dat }
Case :        4
expected  : { http   someserver.com && path/to/firstfile.dat }
processed : { http   someserver.com && /path/to/firstfile.dat }
% TEST_PARSE_URL_PORT: 
  5 errors encountered during TEST_PARSE_URL_PORT tests  
% TEST_PARSE_URL_GENERAL: test failed for URL: http://64.246.30.37/
% TEST_PARSE_URL_GENERAL:   expected: { http   64.246.30.37   }
% TEST_PARSE_URL_GENERAL:        got: { http   64.246.30.37  / }
% TEST_PARSE_URL_GENERAL: test failed for URL: 64.246.30.37:80/
% TEST_PARSE_URL_GENERAL:   expected: {    64.246.30.37 80  }
% TEST_PARSE_URL_GENERAL:        got: {    64.246.30.37 80 / }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://php.net/
% TEST_PARSE_URL_GENERAL:   expected: { http   php.net   }
% TEST_PARSE_URL_GENERAL:        got: { http   php.net  / }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net/
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net   }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net  / }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80  }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 / }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net/index.php
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net  index.php }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net  /index.php }
% TEST_PARSE_URL_GENERAL: test failed for URL: www.php.net:80/?
% TEST_PARSE_URL_GENERAL:   expected: {    www.php.net 80  }
% TEST_PARSE_URL_GENERAL:        got: {    www.php.net 80 / }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net/?
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net   }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net  / }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/?
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80  }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 / }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/index.php
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 index.php }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /index.php }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/foo/bar/index.php
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 foo/bar/index.php }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /foo/bar/index.php }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/this/is/a/very/deep/directory/structure/and/file.php
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 this/is/a/very/deep/directory/structure/and/file.php }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /this/is/a/very/deep/directory/structure/and/file.php }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/this/is/a/very/deep/directory/structure/and/file.php?lots=1&of=2&parameters=3&too=4&here=5
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 this/is/a/very/deep/directory/structure/and/file.php lots=1&of=2&parameters=3&too=4&here=5}
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /this/is/a/very/deep/directory/structure/and/file.php lots=1&of=2&parameters=3&too=4&here=5}
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/this/is/a/very/deep/directory/structure/and/
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 this/is/a/very/deep/directory/structure/and/ }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /this/is/a/very/deep/directory/structure/and/ }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/this/is/a/very/deep/directory/structure/and/file.php
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 this/is/a/very/deep/directory/structure/and/file.php }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /this/is/a/very/deep/directory/structure/and/file.php }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/this/../a/../deep/directory
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 this/../a/../deep/directory }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /this/../a/../deep/directory }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/this/../a/../deep/directory/
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 this/../a/../deep/directory/ }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /this/../a/../deep/directory/ }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/this/is/a/very/deep/directory/../file.php
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 this/is/a/very/deep/directory/../file.php }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /this/is/a/very/deep/directory/../file.php }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/index.php
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 index.php }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /index.php }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/index.php?
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 index.php }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /index.php }
% PARSE_URL: URL fragment left out: #foo
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/#foo
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80  }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 / }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/?#
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80  }
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 / }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/?test=1
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80  test=1}
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 / test=1}
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net/?test=1&
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net   test=1&}
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net  / test=1&}
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/?&
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80  &}
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 / &}
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/index.php?test=1&
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 index.php test=1&}
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /index.php test=1&}
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net/index.php?&
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net  index.php &}
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net  /index.php &}
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/index.php?foo&
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 index.php foo&}
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /index.php foo&}
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net/index.php?&foo
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net  index.php &foo}
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net  /index.php &foo}
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.php.net:80/index.php?test=1&test2=char&test3=mixesCI
% TEST_PARSE_URL_GENERAL:   expected: { http   www.php.net 80 index.php test=1&test2=char&test3=mixesCI}
% TEST_PARSE_URL_GENERAL:        got: { http   www.php.net 80 /index.php test=1&test2=char&test3=mixesCI}
% PARSE_URL: URL fragment left out: #some_page_ref123
% TEST_PARSE_URL_GENERAL: test failed for URL: www.php.net:80/index.php?test=1&test2=char&test3=mixesCI#some_page_ref123
% TEST_PARSE_URL_GENERAL:   expected: {    www.php.net 80 index.php test=1&test2=char&test3=mixesCI}
% TEST_PARSE_URL_GENERAL:        got: {    www.php.net 80 /index.php test=1&test2=char&test3=mixesCI}
% PARSE_URL: URL fragment left out: #some_page_ref123
% TEST_PARSE_URL_GENERAL: test failed for URL: http://secret@www.php.net:80/index.php?test=1&test2=char&test3=mixesCI#some_page_ref123
% TEST_PARSE_URL_GENERAL:   expected: { http secret  www.php.net 80 index.php test=1&test2=char&test3=mixesCI}
% TEST_PARSE_URL_GENERAL:        got: { http secret  www.php.net 80 /index.php test=1&test2=char&test3=mixesCI}
% PARSE_URL: URL fragment left out: #some_page_ref123
% TEST_PARSE_URL_GENERAL: test failed for URL: http://secret:@www.php.net/index.php?test=1&test2=char&test3=mixesCI#some_page_ref123
% TEST_PARSE_URL_GENERAL:   expected: { http secret  www.php.net  index.php test=1&test2=char&test3=mixesCI}
% TEST_PARSE_URL_GENERAL:        got: { http secret  www.php.net  /index.php test=1&test2=char&test3=mixesCI}
% PARSE_URL: URL fragment left out: #some_page_ref123
% TEST_PARSE_URL_GENERAL: test failed for URL: http://:hideout@www.php.net:80/index.php?test=1&test2=char&test3=mixesCI#some_page_ref123
% TEST_PARSE_URL_GENERAL:   expected: { http  hideout www.php.net 80 index.php test=1&test2=char&test3=mixesCI}
% TEST_PARSE_URL_GENERAL:        got: { http  hideout www.php.net 80 /index.php test=1&test2=char&test3=mixesCI}
% PARSE_URL: URL fragment left out: #some_page_ref123
% TEST_PARSE_URL_GENERAL: test failed for URL: http://secret:hideout@www.php.net/index.php?test=1&test2=char&test3=mixesCI#some_page_ref123
% TEST_PARSE_URL_GENERAL:   expected: { http secret hideout www.php.net  index.php test=1&test2=char&test3=mixesCI}
% TEST_PARSE_URL_GENERAL:        got: { http secret hideout www.php.net  /index.php test=1&test2=char&test3=mixesCI}
% PARSE_URL: URL fragment left out: #some_page_ref123
% TEST_PARSE_URL_GENERAL: test failed for URL: http://secret@hideout@www.php.net:80/index.php?test=1&test2=char&test3=mixesCI#some_page_ref123
% TEST_PARSE_URL_GENERAL:   expected: { http secret@hideout  www.php.net 80 index.php test=1&test2=char&test3=mixesCI}
% TEST_PARSE_URL_GENERAL:        got: { http secret@hideout  www.php.net 80 /index.php test=1&test2=char&test3=mixesCI}
% PARSE_URL: URL fragment left out: #some_page_ref123
% TEST_PARSE_URL_GENERAL: test failed for URL: http://secret:hid:out@www.php.net:80/index.php?test=1&test2=char&test3=mixesCI#some_page_ref123
% TEST_PARSE_URL_GENERAL:   expected: { http secret hid:out www.php.net 80 index.php test=1&test2=char&test3=mixesCI}
% TEST_PARSE_URL_GENERAL:        got: { http secret hid:out www.php.net 80 /index.php test=1&test2=char&test3=mixesCI}
% TEST_PARSE_URL_GENERAL: test failed for URL: zlib:/path/to/my/file/file.txt
% TEST_PARSE_URL_GENERAL:   expected: { zlib     path/to/my/file/file.txt }
% TEST_PARSE_URL_GENERAL:        got: { zlib     /path/to/my/file/file.txt }
% TEST_PARSE_URL_GENERAL: test failed for URL: /foo.php?a=b&c=d
% TEST_PARSE_URL_GENERAL:   expected: {      foo.php a=b&c=d}
% TEST_PARSE_URL_GENERAL:        got: {      /foo.php a=b&c=d}
% TEST_PARSE_URL_GENERAL: test failed for URL: file:///path/to/file
% TEST_PARSE_URL_GENERAL:   expected: { file     path/to/file }
% TEST_PARSE_URL_GENERAL:        got: { file     /path/to/file }
% TEST_PARSE_URL_GENERAL: test failed for URL: file:/path/to/file
% TEST_PARSE_URL_GENERAL:   expected: { file     path/to/file }
% TEST_PARSE_URL_GENERAL:        got: { file     /path/to/file }
% TEST_PARSE_URL_GENERAL: test failed for URL: http://1.2.3.4:/abc.asp?a=1&b=2
% TEST_PARSE_URL_GENERAL:   expected: { http   1.2.3.4  abc.asp a=1&b=2}
% TEST_PARSE_URL_GENERAL:        got: { http   1.2.3.4  /abc.asp a=1&b=2}
% PARSE_URL: URL fragment left out: #bar
% TEST_PARSE_URL_GENERAL: test failed for URL: foo+bar://baz@bang/bla
% TEST_PARSE_URL_GENERAL:   expected: { foo+bar baz  bang  bla }
% TEST_PARSE_URL_GENERAL:        got: { foo+bar baz  bang  /bla }
% PARSE_URL: URL contains a control character
% TEST_PARSE_URL_GENERAL: test failed for URL: http://www.google.com/   
% TEST_PARSE_URL_GENERAL:   expected: { http   www.google.com    }
% TEST_PARSE_URL_GENERAL:        got: { http   www.google.com  /         }
% TEST_PARSE_URL_GENERAL: 
  44 errors encountered during TEST_PARSE_URL_GENERAL tests  
...
168/202 Test #168: test_rounding.pro ..................***Failed    0.08 sec
% Compiled module: TEST_ROUNDING.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_ROUNDING_L64: ==========================================================
% TEST_ROUNDING_L64: testing /ROUND
% TEST_ROUNDING_L64: =                                                        =
% TEST_ROUNDING_L64: =  NO errors encountered during TEST_ROUNDING_L64 tests  =
% TEST_ROUNDING_L64: =                                                        =
% TEST_ROUNDING_L64: testing /CEIL
% Compiled module: ERRORS_ADD.
% TEST_ROUNDING_L64: Error on operation : bad value type LONG, case Pos.
% TEST_ROUNDING_L64: =                                                       =
% TEST_ROUNDING_L64: =  1 errors encountered during TEST_ROUNDING_L64 tests  =
% TEST_ROUNDING_L64: =                                                       =
% TEST_ROUNDING_L64: testing /FLOOR
% TEST_ROUNDING_L64: Error on operation : bad value type LONG, case Neg.
% TEST_ROUNDING_L64: =                                                       =
% TEST_ROUNDING_L64: =  1 errors encountered during TEST_ROUNDING_L64 tests  =
% TEST_ROUNDING_L64: =                                                       =
% TEST_ROUNDING_L64: ==========================================================
...
190/202 Test #190: test_total.pro .....................***Failed    7.10 sec
% Compiled module: TEST_TOTAL.
AC 2018 March : this part of the test should be recycle ... TODO !!!
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_TOTAL_NAN_INF: =======================================================
% TEST_TOTAL_NAN_INF: =                                                     =
% TEST_TOTAL_NAN_INF: =  1000 errors encountered during UNFINISHED ! tests  =
% TEST_TOTAL_NAN_INF: =                                                     =
% TEST_TOTAL_NAN_INF: =======================================================
...
199/202 Test #199: test_wordexp.pro ...................***Failed    0.11 sec
% Compiled module: TEST_WORDEXP.
% Compiled module: GDL_IDL_FL.
Working here : /tmp/test_GDL_WordExp
% Compiled module: PATH_SEP.
creating subdirs : normal/ spa ce/ q!mark/ mix,ing :s/
All subdirs well created
Creating some files in each subdirs : a1 a 2 a  3 a;4 a.5 a&6
All files have been created (Local)
% Compiled module: FILE_LINES.
% SPAWN: Error spawning child process: 
Environment variable SHELL | COMSPEC not set.
% Compiled module: ERRORS_ADD.
% TEST_WORDEXP: Error on operation : Problem NbLines Local with file : a1
% TEST_WORDEXP: Error on operation : Problem NbLines Local with file : a 2
% TEST_WORDEXP: Error on operation : Problem NbLines Local with file : a  3
% TEST_WORDEXP: Error on operation : Problem NbLines Local with file : a;4
% TEST_WORDEXP: Error on operation : Problem NbLines Local with file : a.5
% TEST_WORDEXP: Error on operation : Problem NbLines Local with file : a&6
All files have been created (Global)
% SPAWN: Error spawning child process: 
Environment variable SHELL | COMSPEC not set.
% TEST_WORDEXP: Error on operation : Problem NbLines Global with file : a1
% TEST_WORDEXP: Error on operation : Problem NbLines Global with file : a 2
% TEST_WORDEXP: Error on operation : Problem NbLines Global with file : a  3
% TEST_WORDEXP: Error on operation : Problem NbLines Global with file : a;4
% TEST_WORDEXP: Error on operation : Problem NbLines Global with file : a.5
% TEST_WORDEXP: Error on operation : Problem NbLines Global with file : a&6
% Compiled module: BANNER_FOR_TESTSUITE.
% TESTING FILE_BASENAME: 
  NO errors encountered during TESTING FILE_BASENAME tests  
% Compiled module: ERRORS_CUMUL.
% TESTING FILE_DIRNAME: 
  NO errors encountered during TESTING FILE_DIRNAME tests  
% TESTING FILE_SEARCH: 
  NO errors encountered during TESTING FILE_SEARCH tests  
% TESTING FILE_INFO:   NO errors encountered during TESTING FILE_INFO tests  
to be extended ...
```

**Comment by slayoo** [comment] 2018-06-15 07:22
Actually, having:
- testsuite/helpers
- testsuite/release
- testsuite/sandbox

would enable us to at last get rid of the Makefile.am file and simply create list of files in CMake by searching the folder contents - will create a separate issue for it now

**Comment by slayoo** [comment] 2018-06-15 08:04
And big big thanks for working on a Guix package! 
Whenever ready, please let us know so we can update the package list in README.md (or please send a PR with relevant changes to the README.md)

**Comment by alaingdl** [comment] 2018-06-17 21:32
just an advice ! instead 0.9.8.tgz, try current git version ! some of your tests have been improved (not all)

**Comment by daym** [comment] 2018-07-16 10:45
True, with the git version, we get only these test failures:

```
         71 - test_bytscl.pro (Failed) [ed: 1 errors]
         94 - test_fft_leak.pro (Failed) [ed: 13 cases of memory leak]
        123 - test_image_statistics.pro (Failed) [ed: 4 errors; your version of the GraphicsMagick library will truncate images to 16 bits per pixel]
        144 - test_n_tags.pro (Failed) [ed: TEST_NTAGS_MIXING_TYPE]
        179 - test_rounding.pro (Failed) [ed: TEST_NTAGS_BY_TYPE, TEST_ROUNDING_L64]
```

I can't tell how serious those are.

Would it be possible to make a new release which has the other tests (not listed above) succeed?
