### ISSUE TITLE
New user: can't create a plot window

### ISSUE THREAD

**Issue by Genie2000** [gnudatalanguage/gdl#1035] opened 2021-08-01 20:23 UTC
Hi,

I am an IDL user wanting to try out GDL. 

I am using Linux Mint 19.1 Cinnamon. I am normally a Windows user, and my linux knowledge is extremely limited.

I installed GDL using the posted instructions. It seemed to proceed fine.

Below is a copy from the terminal window with some reactions.
***********************************************************************************************************************************************

          (base) **@***********:~/GDL/gdl$ bash quick_start_GDL.sh
          Running current GDL with ./src/pro and ./testsuite in GDL_PATH
          +/home/***/GDL/gdl/src/pro/:+/home/***/GDL/gdl/testsuite/
            GDL - GNU Data Language, Version 1.0.0-rc.3 git
          - For basic information type HELP,/INFO
          - Using WxWidgets as graphics library (windows and widgets).
          - No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
          - Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl
          
          GDL> window  
          ../src/common/object.cpp(251): assert "classTable->Get(m_className) == NULL" failed in Register(): Class "wxCommandEvent" already in RTTI table - have you used IMPLEMENT_DYNAMIC_CLASS() multiple times or linked some object file twice)?
          Gtk-Message: 13:55:56.825: GtkDialog mapped without a transient parent. This is discouraged.
          
          (gdl:9390): Gtk-WARNING **: 13:55:56.834: gtk_window_set_titlebar() called on a realized window
          Gtk-Message: 13:55:56.835: GtkDialog mapped without a transient parent. This is discouraged.
          quick_start_GDL.sh: line 91:  9390 Trace/breakpoint trap   (core dumped) ${Absolute_PATH}/src/gdl
          (base)  **@***********:~/GDL/gdl$ 

***********************************************************************************************************************************************
I get a window with the error message and a "stop" or "continue" option with the former exiting GDL and the former simply repeating the message.

Any help with fixing the issue would be appreciated. 

It might be worth noting that I had previously installed GDL 0.9.7. I had been able to produce a plot window before, but now this is how it looks:

            GDL - GNU Data Language, Version 0.9.7
          
          - For basic information type HELP,/INFO
          - Default library routine search path used (GDL_PATH/IDL_PATH env. var. not set): 
            +/usr/share/gnudatalanguage/lib
          - No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
          - Please report bugs, feature or help requests and patches at:
            http://sourceforge.net/projects/gnudatalanguage/
          
          GDL> window
          % PLplot installation lacks the requested driver: xwin
          % Execution halted at: $MAIN$          
          GDL> 
 
Perhaps I should get rid of this version of GDL. Should I? If so, a little help on exactly the best way to do so would be most helpful.
 
Thanks.

**Comment by alaingdl** [comment] 2021-08-02 09:25
See from here :smile: 
- I suspect you have a Conda env around, which may create side effect(s)
- what do you mean by "installed" ?
 
I strongly suggest : 
- you fully remove the very old 0.9.7 (apt-get remove ... )
- if you "installed" but not compiled GDL, you can easily compile from Git using [Way 1 here](https://github.com/gnudatalanguage/gdl/wiki/GDL-on-Linux#script)

**Comment by Genie2000** [comment] 2021-08-03 02:22
Thanks for the quick reply.

I just removed the old GDL using Linux Mint Software Manager. So far, I get the same errors. 

Indeed I compiled GDL using "Way 1" exactly. Should I repeat any of those steps?

Should I use "bash quick_start_GDL.sh" to start GDL or is there another way?

What can I do about Conda env?

**Comment by Genie2000** [comment] 2021-08-03 02:29
I don't know if this is informative. But this is a "backtrace" which may indicate something useful:
[Backtrace.txt](https://github.com/gnudatalanguage/gdl/files/6920626/Backtrace.txt)

**Comment by GillesDuvert** [comment] 2021-08-03 10:44
Once properly installed, gdl should start by typing 'gdl'. As an IDL user, you know about IDL_STARTUP, !PATH etc, all this is rather well taken into account by GDL.
Now, about the first error (`../src/common/object.cpp(251): assert "classTable->Get(m_className) == NULL" failed` etc) it is a (too fussy) wxWidgets warning, seen with the most recent version of wxWidgets. Normally typing 'continue' in all those annoying messages should permit to, eh, continue with gdl. But indeed this is enormously annoying, as we do not know how to get rid of these spurious wxWidgets messages.
One solution may be to downgrade the wxWidgets version, another to use X11 for "windows".
Provided you compiled GDL with the cmake option '-DX11=ON' *AND* install the plplot 'xwin' driver (apparently not installed by default on your machine) you should be able to have X11 'plot' windows (instead of wxWidgets 'plot' windows) by calling gdl as:
`gdl --no-use-wx`
Hopefully at some point we finally get rid of the idiosyncrasies of wxWidgets and the bad installations of proper plplot drivers by the packagers.

**Comment by Genie2000** [comment] 2021-08-04 22:57
Well, typing 'gdl' doesn't launch it. I still have to use the .sh file.

So I hit "continue" in the error window which doesn't reappear and I can generate a plot. So that is progress.

For updated versions, can I simply repeat the download and compiling process to the same location or is there something else I should do first to make sure there aren't incompatibilities or interferences from the prior compilation?

I am really interested in the HDF5 capabilities. I haven't looked closely at what GDL can do with that yet, but a quick look indicates that it is in a really nascent stage.

**Comment by slayoo** [comment] 2021-08-04 23:10
I guess, @ogressel has the best current knowledge on the level of HDF5 support in GDL and any showstoppers or low hanging fruits for development, Oliver, could you please comment?

**Comment by Genie2000** [comment] 2021-08-08 23:48
Going back to my problem of only being able to run gdl using the quick_start_GLD.sh, I can't seem to launch gdl from the directory that contains it!

            
            (base) tim@tim-Inspiron-15-3567:~$ cd GDL/gdl/build/src
            (base) tim@tim-Inspiron-15-3567:~/GDL/gdl/build/src$ gdl
            
            Command 'gdl' not found, but can be installed with:
            
            sudo apt install gnudatalanguage
            
            (base) tim@tim-Inspiron-15-3567:~/GDL/gdl/build/src$ dir
            antlr  CMakeFiles  cmake_install.cmake	CTestTestfile.cmake  gdl  Makefile
            (base) tim@tim-Inspiron-15-3567:~/GDL/gdl/build/src$ gdl
            
            Command 'gdl' not found, but can be installed with:
            
            sudo apt install gnudatalanguage
            
            (base) tim@tim-Inspiron-15-3567:~/GDL/gdl/build/src$ bash gdl
            gdl: gdl: cannot execute binary file

So, yeah, I don't understand how the .sh file works. 

I have compile gdlde and it launches but wants a GDL_HOME env variable. I can at least do that and have st it to "/home/tim/GDL/gdl/build/src" but that does not seem to satisfy gdlde enough to make GDL run within it, so I think the problems are linked.

Any help to this ignoramus would be appreciated.

**Comment by pjb7687** [comment] 2021-08-09 09:49
@Genie2000 
1. On Linux, you can only launch executables with their full path, even within the same directory. You should:
```
./gdl
```
instead of just `gdl`.

2. To install GDL using build script (build_gdl.sh), you can do following:

```
export INSTALL_PREFIX=/usr/local
sudo scripts/build_gdl.sh install
```

This will install GDL to `/usr/local`. You can additionally set the `GDL_HOME` to `/usr/local`, then GDLDE will recognize the GDL binary.

**Comment by GillesDuvert** [comment] 2021-08-09 10:02
yes, apparently we forgot to document the system installation part in the [wiki](https://github.com/gnudatalanguage/gdl/wiki/GDL-on-Linux), so 'gdl' is not recognised.
Small wiki pages about environment variables, idl_startup file and such, gdlde would be useful.

**Comment by pjb7687** [comment] 2021-08-09 10:03
@Genie2000

Also I tested GDL on my Linux Mint 19.1 Cinnamon but I cannot reproduce the WX problem. Could you run below and post the result here:

```
apt list --installed | grep -e wx -e plplot
```

It would be helpful to debug the issue.

**Comment by Genie2000** [comment] 2021-08-10 01:14
Here is the result:
            WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
            
            libplplot-dev/bionic,now 5.13.0+dfsg-6ubuntu2 amd64 [installed]
            libplplot-lua/bionic,now 5.13.0+dfsg-6ubuntu2 amd64 [installed,automatic]
            libplplot-ocaml/bionic,now 5.13.0+dfsg-6ubuntu2 amd64 [installed,automatic]
            libplplot15/bionic,now 5.13.0+dfsg-6ubuntu2 amd64 [installed,automatic]
            libplplotcxx13/bionic,now 5.13.0+dfsg-6ubuntu2 amd64 [installed,automatic]
            libplplotfortran0/bionic,now 5.13.0+dfsg-6ubuntu2 amd64 [installed,automatic]
            libplplotqt2/bionic,now 5.13.0+dfsg-6ubuntu2 amd64 [installed,automatic]
            libplplotwxwidgets1/bionic,now 5.13.0+dfsg-6ubuntu2 amd64 [installed,automatic]
            libwxbase3.0-0v5/bionic,now 3.0.4+dfsg-3 amd64 [installed,automatic]
            libwxbase3.0-dev/bionic,now 3.0.4+dfsg-3 amd64 [installed,automatic]
            libwxgtk3.0-0v5/bionic,now 3.0.4+dfsg-3 amd64 [installed,automatic]
            libwxgtk3.0-gtk3-0v5/bionic,now 3.0.4+dfsg-3 amd64 [installed,automatic]
            libwxgtk3.0-gtk3-dev/bionic,now 3.0.4+dfsg-3 amd64 [installed]
            plplot-driver-qt/bionic,now 5.13.0+dfsg-6ubuntu2 amd64 [installed,automatic]
            plplot-driver-wxwidgets/bionic,now 5.13.0+dfsg-6ubuntu2 amd64 [installed,automatic]
            plplot-driver-xwin/bionic,now 5.13.0+dfsg-6ubuntu2 amd64 [installed]
            wx-common/bionic,now 3.0.4+dfsg-3 amd64 [installed,automatic]
            wx3.0-headers/bionic,bionic,now 3.0.4+dfsg-3 all [installed,automatic]

**Comment by pjb7687** [comment] 2021-08-10 13:26
@GillesDuvert I have exactly the same wx versions installed on my testing envrionment but I don't get the error. I suspect this is perhaps due to a linking problem?

@Genie2000 Could you upload below two files:

```
build/src/CMakeFiles/gdl.dir/link.txt
build/CMakeCache.txt
```

so that I can further investigate the problem? Thanks!

**Comment by GillesDuvert** [comment] 2021-08-10 14:29
@pjb7687 the 'error' comes from GTK, actually, and AIFAIK is due to a mismatch between the GTK version used by wxWidgets library and the one used when linking GDL, indeed link.txt is the culprit. But, as GDL does not know about GTK, how do we get into such trouble?

**Comment by ogressel** [comment] 2021-08-10 14:31
> I guess, @ogressel has the best current knowledge on the level of HDF5 support in GDL and any showstoppers or low hanging fruits for development, Oliver, could you please comment?

Support for HDF5 is indeed *very* basic at the moment. Adding wrappers for low-level routines should be straightforward (some that I use myself are on my to-do list already).

Reading string data basically implements code from a HDF5-Tutorial and currently only works for one-dimensional dataspaces. I plan to generalize the code to work with arbitrary dataspaces (and possibly also array datatypes).

Another possible improvement pertains to compound data types, which I need for reading file headers, so something else on my to-do list (for now, without nesting). 

I have personally been using HDF5 with IDL for nearly fivteen years now, so I hope that my own use cases cover a fair fraction of what people need in general. Cannot say whether it is realistic to approach IDL's capabilities in full, though.

**Comment by Genie2000** [comment] 2021-08-11 01:23
[CMakeCache.txt](https://github.com/gnudatalanguage/gdl/files/6965257/CMakeCache.txt)
[link.txt](https://github.com/gnudatalanguage/gdl/files/6965258/link.txt)

Here are the requested files.

**Comment by pjb7687** [comment] 2021-08-22 20:27
@Genie2000 Thank you so much for the files! Now I can reproduce the problem.

A temporary solution: you can try removing the package `libwxgtk3.0-gtk3-dev` and building GDL again.

@GillesDuvert There are two wxGTK libraries on Ubuntu, one is `libwxgtk3.0-dev`, and the other one is `libwxgtk3.0-gtk3-dev`.
The problem occurs when GDL is linked against the latter: `libwxgtk3.0-gtk3-dev`. GDL only works fine with the former one.

**Comment by pjb7687** [comment] 2021-08-22 21:00
I attached GDB and further investigated the problem.

In short, the problem is due to the version mismatch between the WX versions used by GDL and Plplot.

The Plplot's wx driver (`wxwidgets.so`) has been compiled against `libwxgtk3.0-dev`. It should not be mixed with `libwxgtk3.0-gtk3-dev` when you compile GDL.

**Comment by Genie2000** [comment] 2021-08-23 03:02
OK. That seems to work. I removed the offending package and modified the build_gdl.sh file to install the right one.

I think this clears up this particular issue.
Thank you all very much.

**Comment by slayoo** [comment] 2021-08-23 04:39
Does it mean that libwxgtk3.0-gtk3-dev should be removed from build_gdl.sh like here:
https://github.com/gnudatalanguage/gdl/pull/1076/files
?

**Comment by pjb7687** [comment] 2021-08-23 10:02
The problem seems to be fixed now, so I close this. We could further discuss the patch in #1076.

**Closed as completed by pjb7687** 2021-08-23 10:02 UTC
