### ISSUE TITLE
Assertion failure in write_png etc.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#736] opened 2020-03-30 09:32 UTC
I've been trying to write a PNG file from GDL (0.9.9, built on Manjaro from AUR package) and see the following error every time, and also with write_jpg (I've not tried others).,
````
GDL> img =  bindgen(64,64)
GDL> write_png, 'junk.png', img
% Compiled module: WRITE_PNG.
% WARNING: your version of the ImageMagick library will truncate images to 16 bits per pixel
gdl: magick/image.c:3213: SetImageOpacity: Assertion `image->signature == MagickCoreSignature' failed.
Abort (core dumped)
$
````
GDL was built with ImageMagick support and no GraphicsMagick support (the cmake and make lines are):
````
    cmake -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON=YES -DPYTHONVERSION=3 \
        -DPYTHON_EXECUTABLE=/usr/bin/python3 -DGRAPHICSMAGICK=OFF -DMAGICK=ON \
        -DFFTW=ON -DHDF=OFF  -DHDF5=ON -DGRIB=ON -DUDUNITS=ON ..

    make -j6
````
The *magick* packages installed are:
````
pacman -Qs magick
local/imagemagick 7.0.10.2-2
    An image viewing/manipulation program
local/libmagick6 6.9.11.2-1
    An image viewing/manipulation program (version 6; library)
````
I'm note sure if  GDL or ImageMagick is at fault here.

**Comment by GillesDuvert** [comment] 2020-03-30 10:34
Hi,
This looks like an imageMagick bug that [was patched a good year ago](https://github.com/ImageMagick/ImageMagick/commit/b67f17367ac8993062eed89b86234a007ff89a1a). (it is an assert, so apparently packagers deliver debug versions instead of optimized versions?) . I do not see any way out except an upgrade of the IM library...

**Comment by jtappin** [comment] 2020-03-30 14:04
Thanks.

Unfortunately it looks like several key packages, including emacs need libmagick6. I'll try a hint on the Manjaro forums.

Edit:
Looking a little deeper. The libmagick6 package was built within the last 2 weeks, and is listed as a dependency of the AUR gnudatalanguage recipe. Is there a set of cmake options that can be passed to the build to make it use the libraries from imagemagick v7 rather than the old v6 libraries? If so I'll check it out and pass it on the the AUR maintainer.

**Comment by maynardGK** [comment] 2020-03-31 00:14
I don't think you'll have luck using ImageMagick7 until some coding is done in GDL to adapt.  
You can build with GraphicMagick, with possibly better results. see #521

**Comment by alaingdl** [comment] 2020-03-31 00:36
We had that much troubles with IM in the pass (new versions : new regressions; change in interfaces ..) that I adopt GM since a long time, and I have a much more quiet life since :)

**Comment by jtappin** [comment] 2020-03-31 08:41
> I don't think you'll have luck using ImageMagick7 until some coding is done in GDL to adapt.
> You can build with GraphicMagick, with possibly better results. see #521

Alas: out of the frying pan and into the fire:-(
After building with graphicsmagick (graphicsmagick-1.3.35) I get an assertion failure on starting GDL:
````
$ gdl
gdl: magick/semaphore.c:601: LockSemaphoreInfo: Assertion `semaphore_info != (SemaphoreInfo *) NULL' failed.
Aborted (core dumped)
$ 
````
There is some discussion on the [AUR page](https://aur.archlinux.org/packages/gnudatalanguage) giving this as the reason for switching the default to using imagemagick.

**Comment by GillesDuvert** [comment] 2020-03-31 09:24
I forgot to say that "works for me" but indeed with graphicsMagick. (graphicsmagick-1.3.35-1.mga7)
The "semaphore" problem was I believe cured, see #611 , but that will be for 1.0.0rc

**Comment by GillesDuvert** [comment] 2021-03-25 18:16
works on current builds, windows, mac and unix. Closing (even if temporarily)

**Closed as completed by GillesDuvert** 2021-03-25 18:16 UTC
