### ISSUE TITLE
IDL/GDL: FUNCTION: Scalar subscript out of range [>].e (61)

### ISSUE THREAD

**Issue by kkin1995** [gnudatalanguage/gdl#963] opened 2021-06-13 07:35 UTC
I wrote .pro IDL/GDL file called single.pro with a function called SCATTERING and I'm calling the function on a different line.

The function definition is:
```
function scattering, dust, dsun, dstar, sflux, sigma, $    
		albedo, phase, angle, mean_density
```
And, the function is called as follows:
```
f = scattering(dust, dsun, dstar, sflux[iwave], sigma[iwave], albedo, phase, angle[iangle], mean_density)
```

The compilation of the program takes place without error:

```
% Compiled module: SCATTERING.
% Compiled module: $MAIN$.
```

However, upon runtime, the program breaks on the line where I am calling the function SCATTERING()

```
% SCATTERING: Scalar subscript out of range [>].e (61)
```

I looked up this error and found that this can arise due to IDL/GDL's array indexing syntax where array's can be index with [] as well as ().

The IDL documentation says that it is recommended to add the line to prevent this behaviour.
```
COMPILE_OPT STRICTARR
```

However, I am not sure where to add this line. I've tried to add it to the beginning of the file, beginning of the function or even execute this line in the GDL REPL before compiling and running the program, but none of this worked.

Any ideas how to solve this ?

Thanks in advance !

**Comment by alaingdl** [comment] 2021-06-13 08:36
Despite your summary, without the code and the way you call it, especially the index it is not easy to be sure of what happen.
But I think what your mention is not important, and the origin of the problem is just that one/some index are out of range

```
GDL> a=findgen(20)
GDL> b=a[21]
% Scalar subscript out of range [>]: (21)
% Execution halted at: $MAIN$          
```

(21 is above the max possible index in the array, which is 19, range going from 0 to 19 in an array with 20 elements)

I think the very simple way I wrote it would help you. Q.E.D (in French : CQFD)

HTH

PS: be cautious that negative index are possible (modulo of the max)
```
GDL> b=a[-2]
GDL> b
      18.0000
```

**Comment by GillesDuvert** [comment] 2021-06-25 08:53
closed as not a GDL bug

**Closed as completed by GillesDuvert** 2021-06-25 08:53 UTC
Labels: wontfix
