### ISSUE TITLE
!FANCY

### ISSUE THREAD

**Issue by PattiMichelle** [gnudatalanguage/gdl#833] opened 2020-09-29 23:24 UTC
I know this will seem extremely stupid  <<blush>>, but I've been looking everywhere online I can think of in order to contact humans involved with GDL, and this is the closest I've come.  Is there a users forum or a "standard" (non github) homepage?  

I may totally noob, but I've been using IDL for decades (since our VAX 11-785) - so I may be able to also help with code similarity testing (writing programs that break GDL).  I ran into that just now with the IDL system variable "!FANCY"

**% READ_AIJ: Not a legal system variable: !FANCY**

Please forgive my barging in here - I couldn't find humans anywhere else...

Thanks in advance...
PattiM

**Comment by maynardGK** [comment] 2020-09-30 07:12
Hi Patti, 
Most GDL developers reside in Europe, but I'm here in Long Beach, CA.  
As to your specific issue, IDL defines at most 33 system variables in https://www.harrisgeospatial.com/docs/System_Variables.html
and !fancy isn't there.   To get it into your code you should defined it in 
your "GDL_STARTUP" file which would be specific to GDL sessions. 
 Maybe, define it as zero and see where that takes you.

Otherwise, GDL is quite robust for the things it knows how to do, and should fit in well for classic applications; exception to this are certainly of interest, and serious issues are responded to quickly.   
````
GDL> help,/sys,output=sysvar
GDL> help,sysvar
SYSVAR          STRING    = Array[39]
GDL> print,sysvar
 !C             LONG      =            0  !COLOR         STRUCT    = -> !COLOR Array[1]
 !CONST         STRUCT    = -> !CONST Array[1]  !CPU           STRUCT    = -> !CPU Array[1]
 !D             STRUCT    = -> !DEVICE Array[1]
 !DIR           STRING    = 'C:/projects/gdl/install/gdl'
 !DPI           DOUBLE    =        3.1415927  !DTOR          FLOAT     =     0.0174533
 !EDIT_INPUT    INT       =        1  !ERR           LONG      =            0
 !ERROR         LONG      =            0  !ERROR_STATE   STRUCT    = -> !ERROR_STATE Array[1]
 !ERR_STRING    STRING    = ''  !EXCEPT        INT       =        1
 !FALSE         BYTE      =    0  !GDL           STRUCT    = -> !GNUDATALANGUAGE Array[1]
 !GDL_MAPS_DIR  STRING    = 'C:\projects\gdl\install\gdl\share\gnudatalanguage\resourc'...
 !GDL_WARNING   LONG      =            1  !JOURNAL       LONG      =            0
 !MAKE_DLL      STRUCT    = -> !MAKE_DLL Array[1]  !MAP           STRUCT    = -> !MAP Array[1]
 !MORE          INT       =        1  !MOUSE         STRUCT    = -> !MOUSE Array[1]
 !NULL          UNDEFINED = !NULL  !ORDER         LONG      =            0
 !P             STRUCT    = -> !PLT Array[1]
 !PATH          STRING    = 'D:/gdlgit/gdl-master/src/pro/CMprocedures;D:/gdlgit/gdl-m'...
 !PI            FLOAT     =       3.14159  !PROMPT        STRING    = 'GDL> '
 !QUIET         LONG      =            0  !RADEG         FLOAT     =       57.2958
 !STIME         STRING    = ''  !TRUE          BYTE      =    1
 !VALUES        STRUCT    = -> !VALUES Array[1]  !VERSION       STRUCT    = -> !VERSION Array[1]
 !WARN          STRUCT    = -> !WARN Array[1]  !X             STRUCT    = -> !AXIS Array[1]
 !Y             STRUCT    = -> !AXIS Array[1]  !Z             STRUCT    = -> !AXIS Array[1]
GDL>
````

**Comment by alaingdl** [comment] 2020-09-30 07:27
Thanks for the report. Giving feedback here is a very good way to help us (I have few bug reports in my mailbox but too busy those days to report here)

I also used IDL since decades but never used/saw that variable !FANCY and did not find it in the inline IDL documentation, and also nowhere in the pro find in lib/

Nevertheless it is not really a problem to add it in the GDL code, but I have no idea what is related to this variable ! An example with usage would be great.

**Comment by fawltylanguage** [comment] 2020-09-30 10:28
!FANCY was obsoleted in IDL 2: [Obsolete System Variables](https://northstar-www.dartmouth.edu/doc/idl/html_6.2/Obsolete_System_Variables.html)

**Comment by GillesDuvert** [comment] 2020-09-30 10:41
hi @PattiMichelle , thanks and welcome!

If your code contains !FANCY it may also contain other very old  system variables (link by @fawltylanguage above). Indeed, as @maynardGK said, GDL would probably be more clever if it proposed a GDL_STARTUP file containing these equivalents.

So, this is more than a contact, it is an issue :smile: 

IDL 8.4 says 
```
IDL> !FANCY
       1
```

**Comment by slayoo** [comment] 2020-09-30 13:32
> I know this will seem extremely stupid, but I've been looking everywhere online I can think of in order to contact humans involved with GDL, and this is the closest I've come. Is there a users forum or a "standard" (non github) homepage?

We do not have a homepage at present, but:
- there is a mailing list: https://sympa.obspm.fr/wws/subscribe/gdl-announces
- there is a wiki: https://github.com/gnudatalanguage/gdl/wiki
- there is the README.md file: https://github.com/gnudatalanguage/gdl/blob/master/README.md
- ... and the "old" README: https://github.com/gnudatalanguage/gdl/blob/master/README
  (which should likely be merged with README.md)

Contributions very welcome!

There's a list of humans involved with GDL development here:
https://github.com/gnudatalanguage/gdl/blob/master/AUTHORS

and a machine-generated list of code-generating humans here:
https://github.com/gnudatalanguage/gdl/graphs/contributors

Github issue tracking functionality proved to be the easiest way to organise communication and the above replies confirm it - you've just reached most of active GDL developers with this one entry (NB: I'm not really an active developer anymore, just helping with maintenance).

**Comment by PattiMichelle** [comment] 2020-09-30 20:23
Hi M.  It's actually listed in "Obsolete System Variables" in the docs to IDL 7.x (which was the latest version I used regularly).  Though so listed, it, nonetheless, was fully operational in a default IDL install (windows or linux) up until at least, that version.  It may have also been functional in v8.x...  I don't recall.  I used it all the time in my scripts for plotting.

> Hi Patti,
> Most GDL developers reside in Europe, but I'm here in Long Beach, CA.
> As to your specific issue, IDL defines at most 33 system variables in https://www.harrisgeospatial.com/docs/System_Variables.html
> and !fancy isn't there. To get it into your code you should defined it in
> your "GDL_STARTUP" file which would be specific to GDL sessions.
> Maybe, define it as zero and see where that takes you.
> 
> Otherwise, GDL is quite robust for the things it knows how to do, and should fit in well for classic applications; exception to this are certainly of interest, and serious issues are responded to quickly.
> 
> ```
> GDL> help,/sys,output=sysvar
> GDL> help,sysvar
> SYSVAR          STRING    = Array[39]
> GDL> print,sysvar
>  !C             LONG      =            0  !COLOR         STRUCT    = -> !COLOR Array[1]
>  !CONST         STRUCT    = -> !CONST Array[1]  !CPU           STRUCT    = -> !CPU Array[1]
>  !D             STRUCT    = -> !DEVICE Array[1]
>  !DIR           STRING    = 'C:/projects/gdl/install/gdl'
>  !DPI           DOUBLE    =        3.1415927  !DTOR          FLOAT     =     0.0174533
>  !EDIT_INPUT    INT       =        1  !ERR           LONG      =            0
>  !ERROR         LONG      =            0  !ERROR_STATE   STRUCT    = -> !ERROR_STATE Array[1]
>  !ERR_STRING    STRING    = ''  !EXCEPT        INT       =        1
>  !FALSE         BYTE      =    0  !GDL           STRUCT    = -> !GNUDATALANGUAGE Array[1]
>  !GDL_MAPS_DIR  STRING    = 'C:\projects\gdl\install\gdl\share\gnudatalanguage\resourc'...
>  !GDL_WARNING   LONG      =            1  !JOURNAL       LONG      =            0
>  !MAKE_DLL      STRUCT    = -> !MAKE_DLL Array[1]  !MAP           STRUCT    = -> !MAP Array[1]
>  !MORE          INT       =        1  !MOUSE         STRUCT    = -> !MOUSE Array[1]
>  !NULL          UNDEFINED = !NULL  !ORDER         LONG      =            0
>  !P             STRUCT    = -> !PLT Array[1]
>  !PATH          STRING    = 'D:/gdlgit/gdl-master/src/pro/CMprocedures;D:/gdlgit/gdl-m'...
>  !PI            FLOAT     =       3.14159  !PROMPT        STRING    = 'GDL> '
>  !QUIET         LONG      =            0  !RADEG         FLOAT     =       57.2958
>  !STIME         STRING    = ''  !TRUE          BYTE      =    1
>  !VALUES        STRUCT    = -> !VALUES Array[1]  !VERSION       STRUCT    = -> !VERSION Array[1]
>  !WARN          STRUCT    = -> !WARN Array[1]  !X             STRUCT    = -> !AXIS Array[1]
>  !Y             STRUCT    = -> !AXIS Array[1]  !Z             STRUCT    = -> !AXIS Array[1]
> GDL>
> ```

**Comment by PattiMichelle** [comment] 2020-09-30 20:28
Thanks, Alain - I always used it - I *think* it was there in version 8.x, but I *know* it was there in v7.x.  All it does is set the size of the axes, axis label/title fonts, and the required margins around the plot borders (to fit the axes).  I think it called other system variables to set that - it was just either some defaults or a basic algorithm to set those.  Now that I think about it, I don't know if changing, say, the axis character sizes affects the spacing of the plot axes from the boundaries of the plot window.  I'll investigate.

> Thanks for the report. Giving feedback here is a very good way to help us (I have few bug reports in my mailbox but too busy those days to report here)
> 
> I also used IDL since decades but never used/saw that variable !FANCY and did not find it in the inline IDL documentation, and also nowhere in the pro find in lib/
> 
> Nevertheless it is not really a problem to add it in the GDL code, but I have no idea what is related to this variable ! An example with usage would be great.

**Comment by PattiMichelle** [comment] 2020-09-30 20:30
Hi Gilles - COOL!  You did all the investigative work - I think it must be there in a startup file, because even in v7 it was listed as "obsolete" (but was still there).

THANKS!!!!!!!  ::^}}

EDIT:  I never knew what a startup file was - so it must be part of a default install somehow.

> hi @PattiMichelle , thanks and welcome!
> 
> If your code contains !FANCY it may also contain other very old system variables (link by @fawltylanguage above). Indeed, as @maynardGK said, GDL would probably be more clever if it proposed a GDL_STARTUP file containing these equivalents.
> 
> So, this is more than a contact, it is an issue smile
> 
> IDL 8.4 says
> 
> ```
> IDL> !FANCY
>        1
> ```

**Comment by PattiMichelle** [comment] 2020-09-30 20:51
Thanks, Slayoo!  OK, so I wasn't dumb - I was expecting a way to talk about things and ask questions besides "reporting issues."  (esp. user errors).  I wonder if it's worthwhile to have some sort of comment blog or something?  Maintaining a web-facing server for that is a big deal, I know.  Maybe Github has a discussion function?  One thing that comes to mind is an IDE for GDL.  I know IDL 7.x used eclipse.  It seems like it might be possible to do a minimal-setup version of eclipse for GDL and expand over time?

> > I know this will seem extremely stupid, but I've been looking everywhere online I can think of in order to contact humans involved with GDL, and this is the closest I've come. Is there a users forum or a "standard" (non github) homepage?
> 
> We do not have a homepage at present, but:
> 
>     * there is a mailing list: https://sympa.obspm.fr/wws/subscribe/gdl-announces
> 
>     * there is a wiki: https://github.com/gnudatalanguage/gdl/wiki
> 
>     * there is the README.md file: https://github.com/gnudatalanguage/gdl/blob/master/README.md
> 
>     * ... and the "old" README: https://github.com/gnudatalanguage/gdl/blob/master/README
>       (which should likely be merged with README.md)
> 
> 
> Contributions very welcome!
> 
> There's a list of humans involved with GDL development here:
> https://github.com/gnudatalanguage/gdl/blob/master/AUTHORS
> 
> and a machine-generated list of code-generating humans here:
> https://github.com/gnudatalanguage/gdl/graphs/contributors
> 
> Github issue tracking functionality proved to be the easiest way to organise communication and the above replies confirm it - you've just reached most of active GDL developers with this one entry (NB: I'm not really an active developer anymore, just helping with maintenance).

**Comment by slayoo** [comment] 2020-10-01 07:25
> I was expecting a way to talk about things and ask questions besides "reporting issues." (esp. user errors).

Here it is: https://github.com/orgs/gnudatalanguage/teams/gdlteam

Greetings,
Sylwester

**Comment by PattiMichelle** [comment] 2020-10-01 17:38
Thanks S!!   Gilles suggested !FANCY could be added - what's typically the next step?  

EDIT:  I found the teams and stuff.  Added some to my bio.  Good stuff.  Thanks :-}

> > I was expecting a way to talk about things and ask questions besides "reporting issues." (esp. user errors).
> 
> Here it is: https://github.com/orgs/gnudatalanguage/teams/gdlteam
> 
> Greetings,
> Sylwester

**Comment by PattiMichelle** [comment] 2020-10-01 17:39
> Thanks S!! Gilles suggested !FANCY could be added - does that mean it will be? I don't know where !FANCY is kept in IDL - perhaps Gilles does - most importantly, what's the algorithm used? What's the next step?
> 
> > > I was expecting a way to talk about things and ask questions besides "reporting issues." (esp. user errors).
> > 
> > 
> > Here it is: https://github.com/orgs/gnudatalanguage/teams/gdlteam
> > Greetings,
> > Sylwester

**Comment by PattiMichelle** [comment] 2020-10-02 16:56
Thanks, slayoo - I didn't know what the "Close with comment" button meant...  talk about a noob!

**Comment by alaingdl** [comment] 2020-10-28 21:52
I have no problem to add !fancy for compatibility BUT
what would be great is to have few case of effects when !Fancy is switch on.

reading the IDL doc. don't give useful informations (eg changing few values in !P or !X ...)

**Comment by PattiMichelle** [comment] 2020-10-29 00:30
I guess I've been using !FANCY for a loooong time.  It wasn't just on/off - !FANCY is a system variable that was still operational in 8.x even though listed as obsolete.  Changing it to larger integers increased the font size on the axes (for all plots, 2D and 3D).  It also automatically made room on the plot for those larger fonts.  So you could increase !fancy to, say 4 (!fancy=4) and the fonts would be proportionally bigger and the axes moved to allow the fonts to fit.  Title sizes and spacings would also move appropriately so that everything fit (more or less).  So there must have been an algorithm or a look-up table that the code used for each integer value of !FANCY.  That would be the trick in implementing it, I think - figuring out which other system variables to change, and by how much, for each value of !FANCY.

Example:
If someone here has a working IDL install, they could post a simple sine wave **plot** 

a=sin(findgen(100)/20)
plot,a

...with !FANCY=1 (the default) then issue the command **!FANCY=8** and do the plot again.  You'll see what I mean. 
 
Then try a surface plot and/or contour plot the same way.
!FANCY=1
surface,a#a
!FANCY=8
surface,a#a

**Comment by GillesDuvert** [comment] 2020-10-29 18:53
Apparently
!FANCY=6  = !P.CHARSIZE=2 
!FANCY=11 = !P.CHARSIZE=3
!FANCY=16 = !P.CHARSIZE=4 etc
!FANCY=0 makes the plot use the device font
!FANCY=-1 = !P.CHARSIZE=0.5 etc

**Comment by PattiMichelle** [comment] 2020-10-30 01:36
I see that !p.charsize also takes care of the spacing of the axes as well as the title fonts.  Kewl.  I guess a linear interpolation from integer space (for !FANCY) is what they did, because I know !p.charsize accepts float inputs.  I don't know if I ever used float inputs on !FANCY or not... (don't know if it works)   
For !FANCY <>0, it looks like:   !P.CHARSIZE = 0.206 * !FANCY + 0.73      (probably it's just 0.2)

And I don't know what font it selects for !FANCY<>0       
GDL>  !P.CHARSIZE = 2.5
GDL>  print,!P.FONT
GDL>  -1  

I don't know interactions with the "**device**" command.  Probably none.

**Comment by alaingdl** [comment] 2020-11-03 14:22
I was ready to add !fancy but I realized that  the Update of !D was removed from  _prognodeexpr.cpp_ 
and I do not remember why (the technical argument) and where it was moved :(
(seem to be in _gdlgstream.cpp_ but I am not sure we can do that for !Fancy
since it has to update !P without going into it)

**Comment by PattiMichelle** [comment] 2020-11-03 16:30
Hi Alain - I think Gilles suggested adding it in a startup file.  It looks like the simple linear fit to !P.CHARSIZE does the trick - but I don't know if there are other things.  There don't seem to be.  I guess that's what you were saying in your post?  
EDIT:  Oh, I get it - you're asking a C coder for info...

**Comment by GillesDuvert** [comment] 2020-11-03 17:28
Now that we've seen what !FANCY means and to reproduce its behaviour it must be internally available by the plot routines, so Alain was right in adding !FANCY in the C++ code, as a starter. I believe it must be defined in initsysvar.cpp .The location where to check for !FANCY is probably only in gdlSetPlotCharsize() in plotting.hpp as this is always used before any plot. !D is not affected by any setting of !FANCY

**Comment by alaingdl** [comment] 2020-11-03 18:18
It is unclear for me whether this code (gdlSetPlotCharsize()) is checked every time we press enter.
(!stime is change every time)

**Comment by GillesDuvert** [comment] 2020-11-03 21:55
could you be more explicit?

**Closed as completed** 2021-04-19 07:59 UTC
Labels: good first issue
