### ISSUE TITLE
Postscript plot size bug related to xrange setting in log x plots

### ISSUE THREAD

**Issue by Barney-9000** [gnudatalanguage/gdl#1002] opened 2021-07-08 17:01 UTC
Notwithstanding existing postscript quirks (see #850), there is some particularly odd behaviour which seems to depend of the Xrange setting when creating log plots.  Best described in the attached illustration [gdl_test.pdf](https://github.com/gnudatalanguage/gdl/files/6786123/gdl_test.pdf).  Ideally, the postscript should be 16 x 16 cm (as in the IDL example) with the plot size 12x12cm starting at (2,2)cm i.e. centred.  The three plots are shown with a border. The GDL plots are always a little larger than specified in the DEVICE command, in this case 17.85 x 17.39cm instead of 16 x 16cm (upper LH plot).

The weird part is with non-decade settings for the xrange upper limit when log plotting.  For example, xrange = [1.0, 1.0E3] behaves itself.  But when the limit is set to any integer multiple other than 1.0 (or 10.0 etc), in this case 2.0E3, the plot area gets truncated at the xrange limit (upper RH plot).  I tried if for 3.0E3, 4.0E3, etc, same effect. Once you get to 10.0E3 the missing plot area reappears.  Very odd.

Another (much smaller) quirk is the difference in charsize behaviour. Default value of 1.0 is fine for most IDL postscript plots, but with GDL need to set it to 1.5 to get close the IDL character size in the plots.

I've included a code snippet.  To explain what may seem an odd convention: I got into the habit years ago of always working in absolute units (e.g. cm).  I have some top and tail procedures which set the device correctly so that a window is set to (very nearly) the correct cm size and the plots/images/etc appear as specified.  Plot positioning is cm > normal, and images are rescaled on the fly (CONGRID) to fit in the designated space in the window (again cm > normal). When the DEVICE is set to postscript, all images are written to the postscript file at their full resolution.

**Comment by GillesDuvert** [comment] 2021-07-09 21:26
thanks @Barney-9000
concerning the exactness of the printed outputs, I'm afraid there is no way to persuade plplot to plot correctly on its postscript output, as the relationship beween device resolution, device coordinates and plplot coordinates are not visible to the outside, i.e., GDL. This is true also for the font size, that need to be manually adjusted for each plplot dirvers to mimic the (enigmatic) behaviour of IDL, with the added problem that the fonts, including the Hershey fonts, are not the same as IDL.
Perhaps somebody will eventually find a way.
Concerning the box limits, there will be a fix of course.

**Comment by alaingdl** [comment] 2021-07-09 21:30
just a comment : is IDL using some derivated version of the old historical [pgplot](https://sites.astro.caltech.edu/~tjp/pgplot/) ? (which has a licence incompatible with GNU GSL)

**Comment by GillesDuvert** [comment] 2021-07-10 21:28
Dear @Barney-9000 I've looked more into your example. First I see the IDL plot different from PostScript and X11 (due to !P.FONT=0 that cannot be reproduced in GDL due to plplot limitations). But aside that, I do not see any truncation at the upper range limit when the limit is not a power of ten,  as reported?
We should adjust the size of characters to 1.5 for PostScript outputs indeed.

**Comment by Barney-9000** [comment] 2021-07-11 12:33
Odd.  Here's the code with my top-n-tail procedures replaced with the basic commands. Just tried it again and certainly shows the effect: window (X or wx) is fine, but the eps is truncated when the upper limit is not a power of 10.  Something amiss with the Plplot compile under macos?  

!P.Font        =   0
  
!X.THICK = 3
!Y.THICK = 3

xpltdimcm   = 16.0
ypltdimcm   = 16.0

IF (!D.name EQ 'X' OR !D.name EQ 'WIN32' OR !D.name EQ 'MAC') THEN WINDOW, Free=1, Title='gdl_plot_test_log', $
      Xsize=xpltdimcm*!D.X_px_cm, Ysize=ypltdimcm*!D.Y_px_cm

IF (!D.name EQ 'PS') THEN DEVICE,Encaps=2,Filename='gdl_plot_test_log.eps', $
        DECOMPOSED=0, $
        Xsize=xpltdimcm,Ysize=ypltdimcm, $
        /Color,Bits_Per_Pixel=8

xc0 =   2.0  &  xn0=xc0/xpltdimcm    ;  cm -> norm
yc0 =   2.0  &  yn0=yc0/ypltdimcm
xcd =  12.0  &  xnd=xcd/xpltdimcm
ycd =  12.0  &  ynd=ycd/ypltdimcm

xrange = [ 1.0, 3.0E3]          ; try upper limit 1.0E3, 2.0E3, 3.0E3, etc. using Postcript device
yrange=  [ 1.0E-6, 1.0E3]

title    = 'Xrange = '+STRING(xrange, Format='(2(E7.1, 2X))')
subtitle = ''
ytitle   = 'Y'
xtitle   = 'X'
xstyle   = 1 
ystyle   = 1 
charsi   = 1.4
 
PLOT_OO,[0,1],[0,1],/Noerase,/Nodata, $
   Xrange=xrange,Xstyle=xstyle, $
   Yrange=yrange,Ystyle=ystyle, $
   Title=title, $
   Subtitle=subtitle, $
   Xtitle=xtitle,Ytitle=ytitle, $
   Charsize=charsi, $
   Position=[xn0,yn0,(xn0+xnd),(yn0+ynd)], $
   /Normal

IF (!D.name EQ 'PS') THEN DEVICE,/Close

END

**Comment by GillesDuvert** [comment] 2021-07-11 21:13
This is how it gets with SET8PLOT='PS' and Xmax=4E3, linux
![image](https://user-images.githubusercontent.com/33936193/125210008-38770880-e29d-11eb-87fe-2aa330befb2d.png)

I cannot test on a MAC for a few days.

for the record: I believe !D.NAME is 'WIN' not 'WIN32' under windows.

**Comment by Barney-9000** [comment] 2021-07-12 08:57
Yep, that's it. 

 _"I believe !D.NAME is 'WIN' not 'WIN32'"_  Ha, show's how long ago that was when I wrote those snippets. :-)

**Comment by GillesDuvert** [comment] 2021-07-13 20:22
OK, got it. The boxsize is not respected. For PS, SVG and Z devices.

**Comment by GillesDuvert** [comment] 2021-07-15 21:24
BTW there may be hope regarding the respect of true sizes in printed outputs. Stay tuned.

**Comment by Barney-9000** [comment] 2021-07-16 11:14
Absolutely!

**Comment by GillesDuvert** [comment] 2021-07-26 16:45
closed by #1023

**Closed as completed by GillesDuvert** 2021-07-26 16:45 UTC
