### ISSUE TITLE
Axis end-point labels not issued in 3D coordinate systems

### ISSUE THREAD

**Issue by AstroArtie** [gnudatalanguage/gdl#1586] opened 2023-05-02 19:39 UTC
When plotting, e.g., a surface:
`surface,findgen(3,6),ysty=1,xticks=2L,xtickname=['zero','one','two']`
only the first label, 'zero', is rendered, but at x=1!
Somehow GDL accepts any number for xticks, and
`surface,findgen(3,6),ysty=1,xticks=3L,xtickname=['zero','one','two']`
renders 'zero', and 'one' at x=1 and 2, and
`surface,findgen(3,6),ysty=1,xticks=4L,xtickname=['zero','one','two']`
renders 'zero', 'one' and 'two' at x=1, 2 and 3.

The first example should render 'zero', 'one' and 'two' at x=0, 1 and 2.
Your help will be most appreciated.
Regner

**Comment by GillesDuvert** [comment] 2023-11-17 22:29
Apart the different X limits between IDL and GDL in case 2, (the logic of "rounding" the min and max axis values in the absence of XRANGE or /XSTYLE modifiers is not the same --- but it is not a bug) the last changes made in GDL seem to close this issue.

**Closed as completed by GillesDuvert** 2023-11-17 22:29 UTC
Labels: bug, 3D Graphics (T3D), tricky
