### ISSUE TITLE
MS window EXE of GDL ?

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#849] opened 2020-11-13 22:51 UTC
Hi

A colleague ask me for a MS window EXE of GDL.
I look around but was not able to locate one.

Could you help me please ? Thanks !

A.

**Comment by slayoo** [comment] 2020-11-13 23:18
Alain, does this info help: https://github.com/gnudatalanguage/gdl/wiki/GDL-on-Windows ?
(just checked and the download does work)

**Comment by jdtreffert** [comment] 2020-11-14 01:18
I may be missing something - but the current (Eigen 3.3.8 -> 3.3.7 (due to #848) gdl_build.zip for Windows doesn't appear to contain a gdl.exe  There are DLLs but no executable.  Thanks in advance - I'm was a long time IDL user - even made a product based on it and would very much enjoy being able work with GDL

**Comment by slayoo** [comment] 2020-11-14 07:29
Thanks for pointing that out! Unfortunately, we still do not have a mechanism to inform us when anything goes wrong with the Windows builds (#615, help welcome!)

Please try one of the earlier successful builds, e.g.: https://ci.appveyor.com/project/slayoo/gdl/builds/35168429

**Comment by jdtreffert** [comment] 2020-11-14 19:46
Thanks!  Giving it a try now!

**Comment by maynardGK** [comment] 2020-11-15 02:18
The latest build of GDL for windows is the artifact found in the Sep 12 build,
https://ci.appveyor.com/api/buildjobs/7h0v0m6yni4kwa2k/artifacts/gdl_build.zip

This cannot be reproduced as the archival storage of support libraries has been revamped, eliminating the older versions
whose names are hardwired into the build script.  The eigen package used in that is 3.3.5.
The updates needed for current usage will appear in appveor_1.msys of #828 soon, but I anticipate the builds may not 
work well.  Graphicsmagick, for instance, changes at version 30 to where the windows version cannot use it.
Already as shown in the PR, upgrading compilers isn't going well, either.

**Comment by pjb7687** [comment] 2021-02-19 23:48
The latest CI builds now provide the windows binaries, so I close this.

**Closed as completed by pjb7687** 2021-02-19 23:48 UTC
